import { Router, type IRouter } from "express";
import healthRouter from "./health";
import tenantsRouter from "./tenants";
import marketsRouter from "./markets";
import categoriesRouter from "./categories";
import sectionsRouter from "./sections";
import formDefinitionsRouter from "./formDefinitions";
import formInstancesRouter from "./formInstances";
import formEntriesRouter from "./formEntries";
import usersRouter from "./users";
import adminAuthRouter from "./admin-auth";
import permissionsRouter from "./permissions";
import seedRouter from "./seed";
import responsibilitiesRouter from "./responsibilities";
import trainingRouter from "./training";
import cleaningPlanRouter from "./cleaningPlan";
import betriebsbegehungRouter from "./betriebsbegehung";
import produktfehlermeldungRouter from "./produktfehlermeldung";
import probeentnahmeRouter from "./probeentnahme";
import besprechungsprotokollRouter from "./besprechungsprotokoll";
import antiVektorRouter from "./antiVektor";
import gesundheitszeugnisseRouter from "./gesundheitszeugnisse";
import arzneimittelSachkundeRouter from "./arzneimittelSachkunde";
import bescheinigungenRouter from "./bescheinigungen";
import kontrollberichteRouter from "./kontrollberichte";
import warenzustandOGRouter from "./warenzustandOG";
import reinigungTaeglichRouter from "./reinigungTaeglich";
import wareneingangOGRouter from "./wareneingangOG";
import wareneingangTypesRouter from "./wareneingangTypes";
import deviceRouter from "./device";
import mhdKontrolleRouter from "./mhdKontrolle";
import wareBestellungenRouter from "./wareBestellungen";
import wareEinraeumserviceRouter from "./wareEinraeumservice";
import wareMhdRouter from "./wareMhd";
import ladenBestellungRouter from "./ladenBestellung";
import metzReinigungRouter from "./metzReinigung";
import shelfMarkersRouter from "./shelfMarkers";
import oeffnungSalateRouter from "./oeffnungSalate";
import kaesethekeKontrolleRouter from "./kaesethekeKontrolle";
import semmellisteRouter from "./semmelliste";
import eingefrorenesFleischRouter from "./eingefrorenesFleisch";
import rezepturenRouter from "./rezepturen";
import gqBegehungRouter from "./gqBegehung";
import hygienebelehrungAbtRouter from "./hygienebelehrungAbt";
import tuevJahresberichtRouter from "./tuevJahresbericht";
import emailSettingsRouter from "./emailSettings";
import notificationsRouter from "./notifications";
import schulungsAnforderungenRouter from "./schulungsAnforderungen";
import monatsberichtRouter from "./monatsbericht";
import streckenLieferantenRouter from "./streckenLieferanten";
import todoRouter from "./todo";
import feedbackRouter from "./feedback";
import authRouter from "./auth";
import systemResetRouter from "./system-reset";
import moduleVisibilityRouter from "./moduleVisibility";
import projectsRouter from "./projects";
import tempLagerKontrolleRouter from "./tempLagerKontrolle";
import rindfleischEtikettenRouter from "./rindfleischEtiketten";
import sectionVisibilityRouter from "./sectionVisibility";
import planEditorRouter from "./planEditor";
import archivRouter from "./archiv";

const router: IRouter = Router();

router.use(healthRouter);
router.use(tenantsRouter);
router.use(marketsRouter);
router.use(categoriesRouter);
router.use(sectionsRouter);
router.use(formDefinitionsRouter);
router.use(formInstancesRouter);
router.use(formEntriesRouter);
router.use(usersRouter);
router.use(adminAuthRouter);
router.use(permissionsRouter);
router.use(seedRouter);
router.use(responsibilitiesRouter);
router.use(trainingRouter);
router.use(cleaningPlanRouter);
router.use(betriebsbegehungRouter);
router.use(produktfehlermeldungRouter);
router.use(probeentnahmeRouter);
router.use(besprechungsprotokollRouter);
router.use(antiVektorRouter);
router.use(gesundheitszeugnisseRouter);
router.use(arzneimittelSachkundeRouter);
router.use(bescheinigungenRouter);
router.use(kontrollberichteRouter);
router.use(warenzustandOGRouter);
router.use(reinigungTaeglichRouter);
router.use(wareneingangOGRouter);
router.use(wareneingangTypesRouter);
router.use(deviceRouter);
router.use(mhdKontrolleRouter);
router.use(wareBestellungenRouter);
router.use(wareEinraeumserviceRouter);
router.use(wareMhdRouter);
router.use(ladenBestellungRouter);
router.use(metzReinigungRouter);
router.use(shelfMarkersRouter);
router.use(oeffnungSalateRouter);
router.use(kaesethekeKontrolleRouter);
router.use(semmellisteRouter);
router.use(eingefrorenesFleischRouter);
router.use(rezepturenRouter);
router.use(gqBegehungRouter);
router.use(hygienebelehrungAbtRouter);
router.use(tuevJahresberichtRouter);
router.use(emailSettingsRouter);
router.use(notificationsRouter);
router.use(schulungsAnforderungenRouter);
router.use(monatsberichtRouter);
router.use(streckenLieferantenRouter);
router.use(todoRouter);
router.use(feedbackRouter);
router.use(authRouter);
router.use(systemResetRouter);
router.use(moduleVisibilityRouter);
router.use(projectsRouter);
router.use(tempLagerKontrolleRouter);
router.use(rindfleischEtikettenRouter);
router.use(sectionVisibilityRouter);
router.use(planEditorRouter);
router.use(archivRouter);

export default router;
