import { Router, type IRouter } from "express";
import healthRouter from "./health";
import tenantsRouter from "./tenants";
import marketsRouter from "./markets";
import categoriesRouter from "./categories";
import sectionsRouter from "./sections";
import formDefinitionsRouter from "./formDefinitions";
import formInstancesRouter from "./formInstances";
import formEntriesRouter from "./formEntries";
import usersRouter from "./users";
import adminAuthRouter from "./admin-auth";
import permissionsRouter from "./permissions";
import seedRouter from "./seed";
import responsibilitiesRouter from "./responsibilities";
import trainingRouter from "./training";
import cleaningPlanRouter from "./cleaningPlan";
import betriebsbegehungRouter from "./betriebsbegehung";
import produktfehlermeldungRouter from "./produktfehlermeldung";
import probeentnahmeRouter from "./probeentnahme";
import deviceRouter from "./device";

const router: IRouter = Router();

router.use(healthRouter);
router.use(tenantsRouter);
router.use(marketsRouter);
router.use(categoriesRouter);
router.use(sectionsRouter);
router.use(formDefinitionsRouter);
router.use(formInstancesRouter);
router.use(formEntriesRouter);
router.use(usersRouter);
router.use(adminAuthRouter);
router.use(permissionsRouter);
router.use(seedRouter);
router.use(responsibilitiesRouter);
router.use(trainingRouter);
router.use(cleaningPlanRouter);
router.use(betriebsbegehungRouter);
router.use(produktfehlermeldungRouter);
router.use(probeentnahmeRouter);
router.use(deviceRouter);

export default router;
